services:
  app_dev:
    volumes:
      - ${APP_PATH_DEV}:/var/www/app:cached
    environment:
      APP_ENV: local

  node_builder_dev:
    volumes:
      - ${APP_PATH_DEV}:/var/www/app:cached

  nginx:
    image: ${NGINX_IMAGE}
    container_name: nginx_local
    depends_on:
      - app_dev
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites.local:/etc/nginx/conf.d:ro
    networks: [stack]
