services:
  app_dev:
    volumes:
      - ${APP_PATH_DEV}:/var/www/app:delegated

  app_prod:
    volumes:
      - ${APP_PATH_PROD}:/var/www/app:delegated

  node_builder_dev:
    volumes:
      - ${APP_PATH_DEV}:/var/www/app:delegated

  node_builder_prod:
    volumes:
      - ${APP_PATH_PROD}:/var/www/app:delegated

  nginx:
    image: ${NGINX_IMAGE}
    container_name: nginx
    depends_on:
      - app_dev
      - app_prod
      - n8n
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites:/etc/nginx/conf.d:ro
      - /srv/letsencrypt/www:/var/www/certbot:ro
      - /srv/letsencrypt/conf:/etc/letsencrypt:ro
    networks: [stack]

  certbot:
    image: ${CERTBOT_IMAGE}
    container_name: certbot
    volumes:
      - /srv/letsencrypt/www:/var/www/certbot
      - /srv/letsencrypt/conf:/etc/letsencrypt
    networks: [stack]
